# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_mime', models.CharField(max_length=72)),
                ('file_key', models.CharField(max_length=72)),
                ('file_content', models.FileField(null=True, upload_to='files')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
