# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0003_auto_20181014_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_mime',
            new_name='mime',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='unnamed_file', max_length=32),
        ),
    ]
