# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0004_auto_20181015_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
