# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0005_auto_20181016_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='owners',
        ),
    ]
