# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_category', '0001_initial'),
        ('manager_topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(to='manager_category.Category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
