# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_topic', '0002_auto_20180319_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='isArhive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(related_name='topics', to='manager_category.Category'),
        ),
    ]
