# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_topic', '0003_auto_20180319_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='isArhive',
            new_name='is_arhive',
        ),
    ]
