# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_topic', '0006_auto_20180319_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.TextField(default='nothing', max_length=40980, verbose_name='Topic text'),
            preserve_default=False,
        ),
    ]
