# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_topic', '0008_auto_20180522_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e?'),
        ),
        migrations.AddField(
            model_name='topic',
            name='viewcount',
            field=models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b'),
        ),
    ]
